### PR TITLE
update to use default branch from ecosystem

### PR DESCRIPTION
**Pull request by maxandersen**
ecosystem are renaming its branch on May 3rd. Please merge this before this date.
Details at https://github.com/quarkusio/quarkus/issues/16601
cc @gastaldi

### CODE REVIEW

**Comment by SlyngDK** [comment]
@gastaldi build still fails with issues for sonarqube. Maybe a permanent fix this time 😀

**Comment by gastaldi** [comment]
@SlyngDK it seems that the secrets are only available if the source branch for the PR comes from the same repo (not from a fork). We'll have to rethink this approach

**Comment by SlyngDK** [comment]
@gastaldi It is the same issue for branches created by dependabot, in this repo. 
It will be nice to get this issue fixed.

**Comment by SlyngDK** [comment]
@gastaldi That fail original, i have just done a rerun, but same with https://github.com/quarkiverse/quarkus-logging-json/pull/98, which I not  have done a rerun on.

**Comment by gastaldi** [comment]
That's really weird. I followed the instructions in https://sonarcloud.io/project/configuration?analysisMode=GitHubActions&id=quarkiverse_quarkus-logging-json and I see that it passes on the Dependabot PRs in https://sonarcloud.io/project/branches?id=quarkiverse_quarkus-logging-json

**Comment by gastaldi** [comment]
BTW better merge this PR today, we're changing the default branch to `main` in https://github.com/quarkusio/quarkus-ecosystem-ci today

**Pull request merged**
